### ISSUE TITLE
SdFat support?

### ISSUE THREAD

**Issue by BiatuAutMiahn** [takkaO/OpenFontRender#26]
Can you implement SdFat support?

**Comment by takkaO** [comment]
Thank you for using this library 😄

OpenFontRender v1.2 now includes enhanced support for file systems.  
This should allow font files to be loaded on various hardware without library changes.   
Unfortunately, no presets are provided yet, but it should be possible to support the SdFat file system by implementing custom code.   
Please see [document](https://takkao.github.io/OpenFontRender/md_manuals_pages.html)  and [sample code](https://github.com/takkaO/OpenFontRender/tree/master/examples) for more info.  
Welcome your feedback.

Sorry for the crazy slow response.

**Comment by BiatuAutMiahn** [comment]
Albeit slow I appreciate the efforts, thanks for getting it implemented! I don't have the time to test right now as this project was put on the back burner for the time being. But I'll update the thread when I get around to it. Feel free to close this issue.
